In [8]:
import sqlite3
import pandas as pd
import polars as pl
pd.options.mode.chained_assignment = None

import sys
sys.path.append('../')
sys.path.append('../networks')

from functions.env import  DB_SCIENCE_PATH_NEW, GRAPH_RESULTS

conn = sqlite3.connect(DB_SCIENCE_PATH_NEW)

from functions.datamodel import OptimumParameter
from functions.feat_network import get_edge_node_table
from functions.feat_visualization import sygma_graph_leiden


# compute average distance:
import pickle
from tqdm import tqdm
import networkx as nx
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
# Use the filterwarnings function to filter and suppress FutureWarning
warnings.filterwarnings("ignore", category=FutureWarning)

import numpy as np
# Function to calculate cosine similarity between position vectors
def cosine_similarity(vector1, vector2):
    dot_product = np.dot(vector1, vector2)
    norm1 = np.linalg.norm(vector1)
    norm2 = np.linalg.norm(vector2)
    return dot_product / (norm1 * norm2)

In [9]:
import glob

list_df = []
paths = glob.glob('../networks/data/weighted/*')
for path in paths:
    df = pd.read_csv(path, index_col = [0])
    df = df[['wikidata_id', 'meta_occupation']]
    df['meta_occupation'] = df['meta_occupation'].apply(lambda x: x.split(' | '))
    df = df.explode('meta_occupation')
    df = df.reset_index(drop=True)
    df.columns = ['source', 'target']
    df['weight'] = 1
    list_df.append(df)

In [10]:
list_edge_filtered = []
list_nodes = []
for element in tqdm(list_df):
    df_net = pl.from_pandas(element)
    df_edge, df_nodes = get_edge_node_table(df_net)
    df_edge_filter = df_edge[
        df_edge["source"] != df_edge["target"]
    ]

    df_edge_filter = df_edge_filter[
        df_edge_filter["rank_count"] <= 3
    ]

    df_edge_filter = df_edge_filter[['source', 'target', 'weight', 'specificity']].copy()
    #maxtrix = df_edge_filter.pivot(index='source', columns='target', values='weight').fillna(0)
    list_edge_filtered.append(df_edge_filter)
    list_nodes.append(df_nodes)

100%|██████████| 100/100 [00:02<00:00, 48.98it/s]

In [11]:
df_edge_filtered_average = pd.concat([x for x in list_edge_filtered])
df_edge_filtered_average = df_edge_filtered_average.groupby(['source', 'target'])['weight'].sum().reset_index()
df_edge_filtered_average['weight'] = df_edge_filtered_average['weight'] / 100 # divide by the number of occupations to get the mean
df_edge_filtered_average = df_edge_filtered_average.sort_values('weight', ascending=False)
df_edge_filtered_average.to_csv('edges_list_filtered/average_edges_list.csv')


df_nodes_average = pd.concat([x for x in list_nodes])
df_nodes_average = df_nodes_average.groupby(['node'])['sum_weight'].mean().reset_index()

In [12]:
# visualization
df_partition, g = sygma_graph_leiden(
df_edge_filtered_average,
df_nodes_average,
edge_bins=10,
node_bins=10,
filepath='final_graph/average_network_pre_1700.html')

In [13]:
df_partition.to_csv('average_network_partition.csv')

In [20]:
df_occurences = pd.merge(df_nodes_average, df_partition, on = 'node')
df_occurences = df_occurences.sort_values(['community', 'sum_weight'], ascending=(False, False))
df_occurences['sum_weight'] = round(df_occurences['sum_weight'])
df_occurences

                   node  sum_weight  size  community
14        mathematician       498.0   9.0          2
4            astronomer       371.0   9.0          2
16         musicologist        88.0   7.0          2
20            physicist        82.0   7.0          2
15        meteorologist         6.0   3.0          2
8        epidemiologist         1.0   1.0          2
9            geographer       231.0   8.0          1
5              botanist       131.0   8.0          1
0             anatomist        54.0   6.0          1
24            zoologist        49.0   6.0          1
6               chemist        44.0   5.0          1
10            geologist        11.0   4.0          1
18       pharmacologist         5.0   2.0          1
3          art theorist         4.0   2.0          1
17       paleontologist         2.0   1.0          1
11            historian      1210.0  10.0          0
19          philosopher      1152.0  10.0          0
23           theologian      1151.0  10.0          0
12             linguist       238.0   8.0          0
7             economist        34.0   5.0          0
2          archeologist        31.0   5.0          0
1        anthropologist        17.0   4.0          0
21  political scientist         9.0   3.0          0
13             logician         9.0   3.0          0
22          sociologist         3.0   1.0          0

In [14]:
df_partition

    community                 node
0           0          philosopher
1           0           theologian
2           0            historian
3           0             linguist
4           0         archeologist
5           0       anthropologist
6           0            economist
7           0             logician
8           0  political scientist
9           0          sociologist
10          1           geographer
11          1            zoologist
12          1             botanist
13          1            anatomist
14          1              chemist
15          1       pharmacologist
16          1            geologist
17          1       paleontologist
18          1         art theorist
19          2           astronomer
20          2        mathematician
21          2            physicist
22          2         musicologist
23          2        meteorologist
24          2       epidemiologist